version: '3.9'
services:
  db:

    image: postgres:15
    environment:
      POSTGRES_DB: donkey

      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    command: gunicorn server.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file: .env.example

    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend

    command: npm run dev
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  postgres_data:
