# Generated by Django 5.2 on 2025-05-24 01:46

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("characters", "0003_initial"),
        ("images", "0002_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LoreEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("tone", models.CharField(default="mystic", max_length=50)),
                ("epithets", models.JSONField(blank=True, default=list)),
                ("traits", models.JSONField(blank=True, default=list)),
                ("lineage", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="NarrativeEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("scene_summary", models.TextField(blank=True, null=True)),
                ("summary_generated", models.BooleanField(default=False)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="narrative_events",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("prompt", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("generated_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("cover_image_url", models.URLField(blank=True, null=True)),
                ("theme", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=50),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("is_reward", models.BooleanField(default=False)),
                (
                    "reward_reason",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image_caption", models.TextField(blank=True, null=True)),
                (
                    "image_alt_text",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="legacy_stories",
                        to="characters.characterprofile",
                    ),
                ),
                (
                    "characters",
                    models.ManyToManyField(
                        blank=True,
                        related_name="stories",
                        to="characters.characterprofile",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linked_story",
                        to="images.image",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories",
                        to="project.project",
                    ),
                ),
                (
                    "style",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="styled_stories",
                        to="images.prompthelper",
                    ),
                ),
            ],
        ),
    ]
