from django.urls import path
from . import views

from .views import agents

urlpatterns = [
    path("swarm-temporal-report/", agents.swarm_temporal_report),
    path("swarm-memory/", agents.swarm_memory),
    path("swarm-snapshot/<str:date>/", agents.swarm_snapshot_view),
    path("swarm-treaties/", agents.list_treaties),
    path("retire/", agents.retire_agents),
    path("lore/", agents.lore_entries),
    path("lore-epochs/", agents.lore_epochs),
    path("myth-reset-cycle/", agents.myth_reset_cycle),
    path("civilizations/", agents.assistant_civilizations),
    path("retcon-requests/", agents.retcon_requests),
    path("consensus-votes/", agents.consensus_votes),
    path("myth-diplomacy/", agents.myth_diplomacy_sessions),
    path("ritual-collapse/", agents.ritual_collapse_logs),
    path("lore-inheritance/", agents.lore_inheritance_lines),
    path("myth-arenas/", agents.myth_simulation_arenas),
    path("harmonize-global/", agents.harmonize_global),
    path("artifacts/", agents.artifacts),
    path("reincarnations/", agents.reincarnations),
    path("return-cycles/", agents.return_cycles),
    path("belief-clusters/", agents.belief_clusters),
    path("lore-tokens/", agents.lore_tokens),
    path("token-rituals/", agents.token_rituals),
    path("token-votes/", agents.token_votes),
    path("token-signatures/", agents.token_signatures),
    path("myth-verification/", agents.myth_verification),
    path("chronomyth-sync/", agents.chronomyth_sync),
    path("belief-forks/", agents.belief_forks),
    path("myth-collapses/", agents.myth_collapses),
    path("memory-reformations/", agents.memory_reformations),
    path("epistemology/", agents.epistemology),
    path("entanglements/", agents.entanglements),
    path("cognitive-constraints/", agents.cognitive_constraints),
    path("belief-negotiations/", agents.belief_negotiations),
    path("paradox-resolution/", agents.paradox_resolution_attempts),
    path("ontology-audits/", agents.ontology_audits),
    path("biomes/", agents.belief_biomes),
    path("myth-registry/", agents.myth_registry),
    path("lore-anchors/", agents.lore_anchors),
    path("ritual-compliance/", agents.ritual_compliance),
    path("clusters/", agents.list_clusters),
    path("clusters/<uuid:id>/", agents.cluster_detail_view),
    path("", agents.list_agents),
    path("<uuid:id>/feedback/", agents.create_agent_feedback),
    path("<uuid:id>/feedback/logs/", agents.agent_feedback_logs),
    path("<uuid:id>/update-from-feedback/", agents.update_agent_from_feedback),
    path("<uuid:id>/train/", agents.train_agent),
    path("<uuid:id>/recommend-training-docs/", agents.recommend_training_docs),
    path("<slug:slug>/", agents.agent_detail_view),
]
