export const ONBOARDING_WORLD = {
  title: "MythOS Onboarding World",
  nodes: [
    {
      slug: "mythpath",
      title: "Mythpath",
      description: "Define your guiding instinct",
      emoji: "\uD83E\uDDED",
      goal: "Define your guiding instinct",
    },
    {
      slug: "world",
      title: "World Map",
      description: "Orient your assistant in a domain",
      emoji: "\uD83D\uDDFA\uFE0F",
      goal: "Orient your assistant in a domain",
    },
    {
      slug: "glossary",
      title: "Glossary",
      description: "Start teaching key terms",
      emoji: "\uD83D\uDCD8",
      goal: "Start teaching key terms",
    },
    {
      slug: "archetype",
      title: "Archetype",
      description: "Pick a behavior/personality profile",
      emoji: "\uD83E\uDDEC",
      goal: "Pick a behavior/personality profile",
    },
    {
      slug: "summon",
      title: "Summoning",
      description: "Create your assistant",
      emoji: "\uD83C\uDF00",
      goal: "Create your assistant",
    },
    {
      slug: "personality",
      title: "Personality",
      description: "Choose avatar and tone",
      emoji: "\uD83E\uDDE0",
      goal: "Choose avatar and tone",
    },
    {
      slug: "wizard",
      title: "Wizard",
      description: "Configure advanced skills",
      emoji: "\uD83E\uDDD9",
      goal: "Configure advanced skills (optional)",
    },
    {
      slug: "ritual",
      title: "Ritual",
      description: "Final review and launch",
      emoji: "\uD83E\uDA84",
      goal: "Final review and launch",
    },
  ],
};
