ONBOARDING_WORLD = {
    "title": "MythOS Onboarding World",
    "welcome": "Welcome to the MythOS Onboarding World!",
    "nodes": [
        {
            "slug": "mythpath",
            "title": "Mythpath",
            "description": "Define your guiding instinct",
            "emoji": "\U0001f9ed",
            "goal": "Define your guiding instinct",
            "ui_label": "Assistant Role",
            "tooltip": "Pick what kind of assistant you're creating — like a planner, researcher, or teacher.",
        },
        {
            "slug": "world",
            "title": "World Map",
            "description": "Orient your assistant in a domain",
            "emoji": "\U0001f5fa\ufe0f",
            "goal": "Orient your assistant in a domain",
            "ui_label": "Domain",
            "tooltip": "Give your assistant some background context for its expertise.",
        },
        {
            "slug": "glossary",
            "title": "Glossary",
            "description": "Start teaching key terms",
            "emoji": "\U0001f4d8",
            "goal": "Start teaching key terms",
            "ui_label": "Key Terms",
            "tooltip": "Introduce important terminology so the assistant speaks your language.",
        },
        {
            "slug": "archetype",
            "title": "Archetype",
            "description": "Pick a behavior/personality profile",
            "emoji": "\U0001f9ec",
            "goal": "Pick a behavior/personality profile",
            "ui_label": "Personality",
            "tooltip": "Choose a style or persona that matches your needs.",
        },
        {
            "slug": "summon",
            "title": "Summoning",
            "description": "Create your assistant",
            "emoji": "\U0001f300",
            "goal": "Create your assistant",
            "ui_label": "Create Assistant",
            "tooltip": "Bring your assistant to life with a name and description.",
        },
        {
            "slug": "personality",
            "title": "Personality",
            "description": "Choose avatar and tone",
            "emoji": "\U0001f9e0",
            "goal": "Choose avatar and tone",
            "ui_label": "Avatar & Tone",
            "tooltip": "Pick how your assistant looks and communicates.",
        },
        {
            "slug": "wizard",
            "title": "Wizard",
            "description": "Configure advanced skills",
            "emoji": "\U0001f9d9",
            "goal": "Configure advanced skills (optional)",
            "ui_label": "Setup Wizard",
            "tooltip": "Walk through setup with helpful suggestions from your AI.",
        },
        {
            "slug": "ritual",
            "title": "Ritual",
            "description": "Final review and launch",
            "emoji": "\U0001fa84",
            "goal": "Final review and launch",
            "ui_label": "Final Step",
            "tooltip": "The last step that completes your assistant's setup.",
        },
    ],
    "video": None,
}

STEPS = [node["slug"] for node in ONBOARDING_WORLD["nodes"]]
