name: Auto Merge Dependabot

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  automerge:
    if: >-
      ${ { github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.pull_requests[0] && github.event.workflow_run.pull_requests[0].head.repo.full_name == github.repository } }
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.workflow_run.pull_requests[0];
            if (!pr) { console.log('No PR'); return; }
            const {data: info} = await github.rest.pulls.get({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number
            });
            if (info.user.login !== 'dependabot[bot]') {
              console.log('Not dependabot');
              return;
            }
            await github.rest.pulls.merge({
              owner: pr.base.repo.owner.login,
              repo: pr.base.repo.name,
              pull_number: pr.number,
              merge_method: 'squash'
            });
