name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.11']
        node-version: ['20']
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install backend deps
        run: pip install -r backend/requirements.txt
      - name: Install frontend deps
        run: npm install
        working-directory: frontend
      - name: Run migrations
        run: python backend/manage.py migrate --noinput
      - name: Lint backend
        run: black --check backend
      - name: Lint frontend
        run: npm run lint
        working-directory: frontend
      - name: Run backend tests
        run: pytest backend
      - name: Run frontend tests
        run: npm test -- --watch=false
        working-directory: frontend
