name: Deploy

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/deploy.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/backend:latest
            ghcr.io/${{ github.repository }}/frontend:latest
          context: .
      - name: Deploy to staging
        run: |
          ssh ${{ secrets.STAGING_HOST }} 'cd /opt/mythos && docker-compose pull && docker-compose up -d'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_KEY }}
