name: Daily Smoke Test

on:
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm install
        working-directory: frontend
      - name: Run Cypress smoke suite
        run: npx cypress run --spec "frontend/cypress/e2e/smoke.cy.js"
